In [1]:
import pandas as pd

In [2]:
pd.read_csv('../raw/CRMLSListing202602.csv', encoding='latin1')

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,2450450.0,1156242329,NaN,NaN,Shirley,Slee,33.165370,-117.331031,1890 Basswood Avenue,Residential,...,NaN,NaN,2.0,Carlsbad Unified,92008,NaN,0.00,10700.0,NaN,1890 Basswood Avenue
1,3400000.0,1156239727,NaN,NaN,Aimee,Edsall,35.534963,-120.770372,3210 Cloudy Meadow Road,Residential,...,1.0,False,3.0,Templeton Unified,93465,NaN,1239.58,1742400.0,NaN,3210 Cloudy Meadow Road
2,8900000.0,1156230852,NaN,NaN,Lisa,Guasti,33.089588,-116.792932,20655 Sutherland Dam Road,Residential,...,2.0,NaN,4.0,Ramona Unified,92065,NaN,0.00,15333120.0,NaN,20655 Sutherland Dam Road
3,539000.0,1156224808,NaN,NaN,Antonietta,Lauro,33.783566,-118.151611,1335 Newport Avenue 202,Residential,...,NaN,False,2.0,Long Beach Unified,90804,NaN,425.00,17977.0,NaN,1335 Newport Avenue 202
4,745000.0,1156111813,NaN,NaN,Hannah,Atchison,35.403224,-120.863022,440 Panay,Residential,...,2.0,False,1.0,San Luis Coastal Unified,93442,NaN,0.00,2800.0,NaN,440 Panay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32184,4950.0,1149458718,NaN,NaN,Alphonso,Lascano,34.044402,-118.365074,1716 S Genesee Avenue,ResidentialLease,...,NaN,False,NaN,NaN,90019,NaN,NaN,4886.0,NaN,1716 S Genesee Avenue
32185,1699.0,1146439434,NaN,NaN,Gene,Smith,38.115612,-122.267146,124 Benson Ave,ResidentialLease,...,NaN,False,1.0,NaN,94590,NaN,NaN,15681.0,NaN,124 Benson Ave
32186,350000.0,1146104836,NaN,NaN,Jason,Lipovsky,33.139128,-117.053881,475 N Midway Drive 169,Residential,...,0.0,NaN,0.0,Escondido Union,92027,NaN,400.00,261360.0,NaN,475 N Midway Drive 169
32187,1325.0,1107246684,NaN,NaN,Kathy,Lund,32.572312,-117.034778,4589 Casa nova ct,ResidentialLease,...,5.0,False,2.0,Other,92154,NaN,0.00,2224.0,NaN,4589 Casa nova ct
32188,6000.0,1063377179,NaN,NaN,Jaime,Rook,33.162293,-117.266434,4717 Majorca Way,ResidentialLease,...,NaN,NaN,2.0,Oceanside Unified,92056,NaN,NaN,3519.0,NaN,4717 Majorca Way

In [3]:

import glob

PATH = r"C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw/"

# Match ALL listing files
files = glob.glob(PATH + "CRMLSListing*")

print("Files found:", files)

if not files:
    raise ValueError("No LISTING files found. Check your folder or filename pattern.")

df_listed = pd.concat([pd.read_csv(f, encoding='latin1') for f in files], ignore_index=True)

print(df_listed.head())
print(df_listed.shape)

df_listed.to_csv("combined_listed.csv", index=False)
df_listed

Files found: ['C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202401.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202402.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202403.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202404.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202405.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202406.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202407.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202408.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202409.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202410.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202411.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202412.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202501.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202502.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202503.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202504.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202505.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202506.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202507.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202508.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202509.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202510.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202511.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202512.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202601.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSListing202602.csv']
   OriginalListPrice  ListingKey                        ListAgentEmail  \
0            90000.0  1075010398                miriamlara03@gmail.com
1          1500000.0  1074974457                  janelle@judsonre.com
2          1340000.0  1074973329                    haleh360@Gmail.com
3          2500000.0  1074954552  Reneechen@yourhomesoldguaranteed.com
4          3150000.0  1074936537                      anader@dppre.com

  CloseDate  ClosePrice ListAgentFirstName ListAgentLastName   Latitude  \
0       NaN         NaN             Miriam              Lara  34.097939
1       NaN         NaN            Janelle            Judson  33.121241
2       NaN         NaN              Haleh       Dowlatshahi  34.052207
3       NaN         NaN              Renee              Chen  33.496363
4       NaN         NaN           Margaret             Nader  34.119345

    Longitude                UnparsedAddress  ... MainLevelBedrooms  \
0 -117.909653                1045 N Azusa 61  ...               NaN
1 -117.081614                            NaN  ...               NaN
2 -118.408445  2220 Avenue Of The Stars 2704  ...               NaN
3 -117.691677                   16 Palisades  ...               0.0
4 -118.111254              1615 Waverly Road  ...               NaN

   NewConstructionYN  GarageSpaces     HighSchoolDistrict PostalCode  \
0                NaN           2.0  Covina Valley Unified      91722
1                NaN           NaN                    NaN      92025
2              False           NaN                    NaN      90067
3              False           3.0     Capistrano Unified      92677
4                NaN           2.0                    NaN      91108

  BuyerOfficeName.1 AssociationFee LotSizeSquareFeet  \
0               NaN            0.0               NaN
1               NaN            0.0               NaN
2               NaN         2105.0          177861.0
3               NaN          254.0            5300.0
4               NaN            NaN            9404.0

  MiddleOrJuniorSchoolDistrict              UnparsedAddress.1
0                          NaN                1045 N Azusa 61
1                          NaN                            NaN
2                          NaN  2220 Avenue Of The Stars 2704
3                          NaN                   16 Palisades
4                          NaN              1615 Waverly Road

[5 rows x 84 columns]
(814726, 84)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814721,4950.0,1149458718,NaN,NaN,NaN,Alphonso,Lascano,34.044402,-118.365074,1716 S Genesee Avenue,...,NaN,False,NaN,NaN,90019,NaN,NaN,4886.0,NaN,1716 S Genesee Avenue
814722,1699.0,1146439434,NaN,NaN,NaN,Gene,Smith,38.115612,-122.267146,124 Benson Ave,...,NaN,False,1.0,NaN,94590,NaN,NaN,15681.0,NaN,124 Benson Ave
814723,350000.0,1146104836,NaN,NaN,NaN,Jason,Lipovsky,33.139128,-117.053881,475 N Midway Drive 169,...,0.0,NaN,0.0,Escondido Union,92027,NaN,400.0,261360.0,NaN,475 N Midway Drive 169
814724,1325.0,1107246684,NaN,NaN,NaN,Kathy,Lund,32.572312,-117.034778,4589 Casa nova ct,...,5.0,False,2.0,Other,92154,NaN,0.0,2224.0,NaN,4589 Casa nova ct
814725,6000.0,1063377179,NaN,NaN,NaN,Jaime,Rook,33.162293,-117.266434,4717 Majorca Way,...,NaN,NaN,2.0,Oceanside Unified,92056,NaN,NaN,3519.0,NaN,4717 Majorca Way

In [4]:
pd.read_csv('combined_listed.csv').head()

C:\Users\alexa\AppData\Local\Temp\ipykernel_17352\1263627975.py:1: DtypeWarning: Columns (2,43) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('combined_listed.csv').head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road